### PR TITLE
Allow bot.default to handle messages in groups

### PR DESCRIPTION
**Pull request by ogroleg**
Thus allowing to handle all text messages, except defined commands

### CODE REVIEW

**Comment by szastupov** [comment]
Hi! Well, apparently it breaks a lot of things :) See tests.

**Comment by ogroleg** [comment]
@szastupov, how about this version?

**Comment by szastupov** [comment]
While It doesn't break anything, I can't accept it as is. Group chats are skipped intentionally in default callback - if you have multiple bots in the same chat, *all* bots will receive /slash commands, leading to lots of noice.

**Comment by ogroleg** [comment]
But if bot is explicitly subscribed to default callback, does not it mean that _all_ unhandled events should arrive there? However, some of them are dropped.
As another way, default_group may be added, but it does not look like a clean solution.

**Comment by szastupov** [comment]
Yeah, default_group sucks. So what if we add a flag to bot that enables default handling in groups? like Bot(..., default_in_groups=True).

**Comment by ogroleg** [comment]
Good idea, I've rewritten commit, tests are passing, but build fails due to code style problem at lines that was not touched by this commit.

**Comment by szastupov** [comment]
Looks good! I'm gonna merge it and fix flake8 error myself. Thanks!

**Comment by ogroleg** [comment]
It seems like documentation should also be updated.

**Pull request merged**
