### PR TITLE
Move version to separate file

### PR DESCRIPTION
**Pull request by SijmenSchoon**
This way, setup.py and Sphinx can share the same version number without having to update them separately.

### CODE REVIEW

**Comment by szastupov** [comment]
Hm, maybe rewrite file constructs to use with statement? i.e.:

```python
with open('VERSION') as version_file:
    version = version_file.read().strip()
```

Just looks a bit prettier :) Sorry for being too pedantic 🤓

**Comment by SijmenSchoon** [comment]
I'd love to do that, but that only works in Python 2.5 and later, and I'd like to make it as version-unspecific as possible. It's setup.py we're talking about, after all.

**Comment by szastupov** [comment]
Yeah, but aiotg's minimum requirement is Python 3.5 (because of async/await) so there is no need to maintain strict compatibility.

Or, as an alternative, you can drop .close() altogether.

But if you really want it you can keep it as is, not a big deal :)

**Comment by SijmenSchoon** [comment]
It doesn't really matter for users, but I have no idea what consequences it will have for PyPI

**Comment by szastupov** [comment]
Ok then. Merging it. Thanks!

**Pull request merged**
