### PR TITLE
aiosocksy is deprecated and archived #82

### PR DESCRIPTION
**Pull request by keyiflerolsun**
change lib

### CODE REVIEW

**Comment by szastupov** [comment]
Is it a drop in replacement?

**Comment by keyiflerolsun** [comment]
same library.  continues to be developed under a different name.

**Comment by szastupov** [comment]
Yeah, but aren't at least imports need to be changed?

**Comment by keyiflerolsun** [comment]
uups, i tested now; unfortunately yes 😞

**Pull request closed without merging**
